# Intrinio API
#
# Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
#
# OpenAPI spec version: 2.9.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApiResponseFilingFundamentals Class
#'
#' @field fundamentals 
#' @field filing 
#' @field next_page 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApiResponseFilingFundamentals <- R6::R6Class(
  'ApiResponseFilingFundamentals',
  public = list(
    `fundamentals` = NULL,
    `filing` = NULL,
    `next_page` = NULL,
    initialize = function(`fundamentals`, `filing`, `next_page`){
      if (!missing(`fundamentals`)) {
        stopifnot(is.list(`fundamentals`))
        lapply(`fundamentals`, function(x) stopifnot(R6::is.R6(x)))
        self$`fundamentals` <- `fundamentals`
      }
      if (!missing(`filing`)) {
        stopifnot(R6::is.R6(`filing`))
        self$`filing` <- `filing`
      }
      if (!missing(`next_page`)) {
        stopifnot(is.character(`next_page`), length(`next_page`) == 1)
        self$`next_page` <- `next_page`
      }
    },
    toJSON = function() {
      ApiResponseFilingFundamentalsObject <- list()
      if (!is.null(self$`fundamentals`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`fundamentals`) && ((length(self$`fundamentals`) == 0) || ((length(self$`fundamentals`) != 0 && R6::is.R6(self$`fundamentals`[[1]]))))) {
          ApiResponseFilingFundamentalsObject[['fundamentals']] <- lapply(self$`fundamentals`, function(x) x$toJSON())
        } else {
          ApiResponseFilingFundamentalsObject[['fundamentals']] <- jsonlite::toJSON(self$`fundamentals`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`filing`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`filing`) && ((length(self$`filing`) == 0) || ((length(self$`filing`) != 0 && R6::is.R6(self$`filing`[[1]]))))) {
          ApiResponseFilingFundamentalsObject[['filing']] <- lapply(self$`filing`, function(x) x$toJSON())
        } else {
          ApiResponseFilingFundamentalsObject[['filing']] <- jsonlite::toJSON(self$`filing`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`next_page`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`next_page`) && ((length(self$`next_page`) == 0) || ((length(self$`next_page`) != 0 && R6::is.R6(self$`next_page`[[1]]))))) {
          ApiResponseFilingFundamentalsObject[['next_page']] <- lapply(self$`next_page`, function(x) x$toJSON())
        } else {
          ApiResponseFilingFundamentalsObject[['next_page']] <- jsonlite::toJSON(self$`next_page`, auto_unbox = TRUE)
        }
      }

      ApiResponseFilingFundamentalsObject
    },
    fromJSON = function(ApiResponseFilingFundamentalsJson) {
      ApiResponseFilingFundamentalsObject <- jsonlite::fromJSON(ApiResponseFilingFundamentalsJson)
      if (!is.null(ApiResponseFilingFundamentalsObject$`fundamentals`)) {
        self$`fundamentals` <- ApiResponseFilingFundamentalsObject$`fundamentals`
      }
      if (!is.null(ApiResponseFilingFundamentalsObject$`filing`)) {
        self$`filing` <- ApiResponseFilingFundamentalsObject$`filing`
      }
      if (!is.null(ApiResponseFilingFundamentalsObject$`next_page`)) {
        self$`next_page` <- ApiResponseFilingFundamentalsObject$`next_page`
      }
    },
    toJSONString = function() {
      jsonlite::toJSON(self$toJSON(), auto_unbox = TRUE, pretty = TRUE)
    },
    fromJSONString = function(ApiResponseFilingFundamentalsJson) {
      ApiResponseFilingFundamentalsObject <- jsonlite::fromJSON(ApiResponseFilingFundamentalsJson)
      self$`fundamentals` <- lapply(ApiResponseFilingFundamentalsObject$`fundamentals`, function(x) FundamentalSummary$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      FilingSummaryObject <- FilingSummary$new()
      self$`filing` <- FilingSummaryObject$fromJSON(jsonlite::toJSON(ApiResponseFilingFundamentalsObject$filing, auto_unbox = TRUE))
      self$`next_page` <- ApiResponseFilingFundamentalsObject$`next_page`
    }
  )
)
