# Intrinio API
#
# Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
#
# OpenAPI spec version: 2.9.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApiResponseSecuritiesSearch Class
#'
#' @field securities 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApiResponseSecuritiesSearch <- R6::R6Class(
  'ApiResponseSecuritiesSearch',
  public = list(
    `securities` = NULL,
    initialize = function(`securities`){
      if (!missing(`securities`)) {
        stopifnot(is.list(`securities`))
        lapply(`securities`, function(x) stopifnot(R6::is.R6(x)))
        self$`securities` <- `securities`
      }
    },
    toJSON = function() {
      ApiResponseSecuritiesSearchObject <- list()
      if (!is.null(self$`securities`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`securities`) && ((length(self$`securities`) == 0) || ((length(self$`securities`) != 0 && R6::is.R6(self$`securities`[[1]]))))) {
          ApiResponseSecuritiesSearchObject[['securities']] <- lapply(self$`securities`, function(x) x$toJSON())
        } else {
          ApiResponseSecuritiesSearchObject[['securities']] <- jsonlite::toJSON(self$`securities`, auto_unbox = TRUE)
        }
      }

      ApiResponseSecuritiesSearchObject
    },
    fromJSON = function(ApiResponseSecuritiesSearchJson) {
      ApiResponseSecuritiesSearchObject <- jsonlite::fromJSON(ApiResponseSecuritiesSearchJson)
      if (!is.null(ApiResponseSecuritiesSearchObject$`securities`)) {
        self$`securities` <- ApiResponseSecuritiesSearchObject$`securities`
      }
    },
    toJSONString = function() {
      jsonlite::toJSON(self$toJSON(), auto_unbox = TRUE, pretty = TRUE)
    },
    fromJSONString = function(ApiResponseSecuritiesSearchJson) {
      ApiResponseSecuritiesSearchObject <- jsonlite::fromJSON(ApiResponseSecuritiesSearchJson)
      self$`securities` <- lapply(ApiResponseSecuritiesSearchObject$`securities`, function(x) SecuritySummary$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
