# Intrinio API
#
# Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://docs.intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
#
# OpenAPI spec version: 2.103.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApiResponseIndexIntervals Class
#'
#' @field intervals 
#' @field next_page 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApiResponseIndexIntervals <- R6::R6Class(
  'ApiResponseIndexIntervals',
  public = list(
    `intervals` = NA,
    `intervals_data_frame` = NULL,
    `next_page` = NA,
    initialize = function(`intervals`, `next_page`){
      if (!missing(`intervals`)) {
        self$`intervals` <- `intervals`
      }
      if (!missing(`next_page`)) {
        self$`next_page` <- `next_page`
      }
    },
    toJSON = function() {
      ApiResponseIndexIntervalsObject <- list()
      if (!is.null(self$`intervals`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`intervals`) && ((length(self$`intervals`) == 0) || ((length(self$`intervals`) != 0 && R6::is.R6(self$`intervals`[[1]]))))) {
          ApiResponseIndexIntervalsObject[['intervals']] <- lapply(self$`intervals`, function(x) x$toJSON())
        } else {
          ApiResponseIndexIntervalsObject[['intervals']] <- jsonlite::toJSON(self$`intervals`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`next_page`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`next_page`) && ((length(self$`next_page`) == 0) || ((length(self$`next_page`) != 0 && R6::is.R6(self$`next_page`[[1]]))))) {
          ApiResponseIndexIntervalsObject[['next_page']] <- lapply(self$`next_page`, function(x) x$toJSON())
        } else {
          ApiResponseIndexIntervalsObject[['next_page']] <- jsonlite::toJSON(self$`next_page`, auto_unbox = TRUE)
        }
      }

      ApiResponseIndexIntervalsObject
    },
    fromJSON = function(ApiResponseIndexIntervalsJson) {
      ApiResponseIndexIntervalsObject <- jsonlite::fromJSON(ApiResponseIndexIntervalsJson)
      if (!is.null(ApiResponseIndexIntervalsObject$`intervals`)) {
        self$`intervals` <- ApiResponseIndexIntervalsObject$`intervals`
      }
      if (!is.null(ApiResponseIndexIntervalsObject$`next_page`)) {
        self$`next_page` <- ApiResponseIndexIntervalsObject$`next_page`
      }
    },
    toJSONString = function() {
      jsonlite::toJSON(self$toJSON(), auto_unbox = TRUE, pretty = TRUE)
    },
    fromJSONString = function(ApiResponseIndexIntervalsJson) {
      ApiResponseIndexIntervalsObject <- jsonlite::fromJSON(ApiResponseIndexIntervalsJson, simplifyDataFrame = FALSE)
      self$setFromList(ApiResponseIndexIntervalsObject)
    },
    setFromList = function(listObject) {


      self$`intervals` <- lapply(listObject$`intervals`, function(x) {
      IndexIntervalObject <- IndexInterval$new()
      IndexIntervalObject$setFromList(x)
      return(IndexIntervalObject)
      })

      intervals_list <- lapply(self$`intervals`, function(x) {
        return(x$getAsList()) 
      })

      self$`intervals_data_frame` <- do.call(rbind, lapply(intervals_list, data.frame))






      if (!is.null(listObject$`next_page`)) {
        self$`next_page` <- listObject$`next_page`
      }
      else {
        self$`next_page` <- NA 
      }

    },
    getAsList = function() {
      listObject = list()
      # listObject[["intervals"]] <- lapply(self$`intervals`, function(o) {
      #  return(o$getAsList())
      # })




        
      listObject[["next_page"]] <- self$`next_page`
      return(listObject)
    }
  )
)
