# Intrinio API
#
# Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
#
# OpenAPI spec version: 2.9.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ApiResponseSecurityEaseOfMovement Class
#'
#' @field technicals 
#' @field indicator 
#' @field security 
#' @field next_page 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApiResponseSecurityEaseOfMovement <- R6::R6Class(
  'ApiResponseSecurityEaseOfMovement',
  public = list(
    `technicals` = NULL,
    `indicator` = NULL,
    `security` = NULL,
    `next_page` = NULL,
    initialize = function(`technicals`, `indicator`, `security`, `next_page`){
      if (!missing(`technicals`)) {
        stopifnot(is.list(`technicals`))
        lapply(`technicals`, function(x) stopifnot(R6::is.R6(x)))
        self$`technicals` <- `technicals`
      }
      if (!missing(`indicator`)) {
        stopifnot(R6::is.R6(`indicator`))
        self$`indicator` <- `indicator`
      }
      if (!missing(`security`)) {
        stopifnot(R6::is.R6(`security`))
        self$`security` <- `security`
      }
      if (!missing(`next_page`)) {
        stopifnot(is.character(`next_page`), length(`next_page`) == 1)
        self$`next_page` <- `next_page`
      }
    },
    toJSON = function() {
      ApiResponseSecurityEaseOfMovementObject <- list()
      if (!is.null(self$`technicals`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`technicals`) && ((length(self$`technicals`) == 0) || ((length(self$`technicals`) != 0 && R6::is.R6(self$`technicals`[[1]]))))) {
          ApiResponseSecurityEaseOfMovementObject[['technicals']] <- lapply(self$`technicals`, function(x) x$toJSON())
        } else {
          ApiResponseSecurityEaseOfMovementObject[['technicals']] <- jsonlite::toJSON(self$`technicals`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`indicator`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`indicator`) && ((length(self$`indicator`) == 0) || ((length(self$`indicator`) != 0 && R6::is.R6(self$`indicator`[[1]]))))) {
          ApiResponseSecurityEaseOfMovementObject[['indicator']] <- lapply(self$`indicator`, function(x) x$toJSON())
        } else {
          ApiResponseSecurityEaseOfMovementObject[['indicator']] <- jsonlite::toJSON(self$`indicator`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`security`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`security`) && ((length(self$`security`) == 0) || ((length(self$`security`) != 0 && R6::is.R6(self$`security`[[1]]))))) {
          ApiResponseSecurityEaseOfMovementObject[['security']] <- lapply(self$`security`, function(x) x$toJSON())
        } else {
          ApiResponseSecurityEaseOfMovementObject[['security']] <- jsonlite::toJSON(self$`security`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`next_page`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`next_page`) && ((length(self$`next_page`) == 0) || ((length(self$`next_page`) != 0 && R6::is.R6(self$`next_page`[[1]]))))) {
          ApiResponseSecurityEaseOfMovementObject[['next_page']] <- lapply(self$`next_page`, function(x) x$toJSON())
        } else {
          ApiResponseSecurityEaseOfMovementObject[['next_page']] <- jsonlite::toJSON(self$`next_page`, auto_unbox = TRUE)
        }
      }

      ApiResponseSecurityEaseOfMovementObject
    },
    fromJSON = function(ApiResponseSecurityEaseOfMovementJson) {
      ApiResponseSecurityEaseOfMovementObject <- jsonlite::fromJSON(ApiResponseSecurityEaseOfMovementJson)
      if (!is.null(ApiResponseSecurityEaseOfMovementObject$`technicals`)) {
        self$`technicals` <- ApiResponseSecurityEaseOfMovementObject$`technicals`
      }
      if (!is.null(ApiResponseSecurityEaseOfMovementObject$`indicator`)) {
        self$`indicator` <- ApiResponseSecurityEaseOfMovementObject$`indicator`
      }
      if (!is.null(ApiResponseSecurityEaseOfMovementObject$`security`)) {
        self$`security` <- ApiResponseSecurityEaseOfMovementObject$`security`
      }
      if (!is.null(ApiResponseSecurityEaseOfMovementObject$`next_page`)) {
        self$`next_page` <- ApiResponseSecurityEaseOfMovementObject$`next_page`
      }
    },
    toJSONString = function() {
      jsonlite::toJSON(self$toJSON(), auto_unbox = TRUE, pretty = TRUE)
    },
    fromJSONString = function(ApiResponseSecurityEaseOfMovementJson) {
      ApiResponseSecurityEaseOfMovementObject <- jsonlite::fromJSON(ApiResponseSecurityEaseOfMovementJson)
      self$`technicals` <- lapply(ApiResponseSecurityEaseOfMovementObject$`technicals`, function(x) EaseOfMovementTechnicalValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      TechnicalIndicatorObject <- TechnicalIndicator$new()
      self$`indicator` <- TechnicalIndicatorObject$fromJSON(jsonlite::toJSON(ApiResponseSecurityEaseOfMovementObject$indicator, auto_unbox = TRUE))
      SecuritySummaryObject <- SecuritySummary$new()
      self$`security` <- SecuritySummaryObject$fromJSON(jsonlite::toJSON(ApiResponseSecurityEaseOfMovementObject$security, auto_unbox = TRUE))
      self$`next_page` <- ApiResponseSecurityEaseOfMovementObject$`next_page`
    }
  )
)
