# Intrinio API
#
# Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
#
# OpenAPI spec version: 2.9.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FilingNoteFiling Class
#'
#' @field cik 
#' @field report_type 
#' @field period_end_date 
#' @field filing_date 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FilingNoteFiling <- R6::R6Class(
  'FilingNoteFiling',
  public = list(
    `cik` = NULL,
    `report_type` = NULL,
    `period_end_date` = NULL,
    `filing_date` = NULL,
    initialize = function(`cik`, `report_type`, `period_end_date`, `filing_date`){
      if (!missing(`cik`)) {
        stopifnot(is.character(`cik`), length(`cik`) == 1)
        self$`cik` <- `cik`
      }
      if (!missing(`report_type`)) {
        stopifnot(is.character(`report_type`), length(`report_type`) == 1)
        self$`report_type` <- `report_type`
      }
      if (!missing(`period_end_date`)) {
        stopifnot(is.character(`period_end_date`), length(`period_end_date`) == 1)
        stopifnot(R6::is.R6(`period_end_date`))
        self$`period_end_date` <- `period_end_date`
      }
      if (!missing(`filing_date`)) {
        stopifnot(is.character(`filing_date`), length(`filing_date`) == 1)
        stopifnot(R6::is.R6(`filing_date`))
        self$`filing_date` <- `filing_date`
      }
    },
    toJSON = function() {
      FilingNoteFilingObject <- list()
      if (!is.null(self$`cik`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`cik`) && ((length(self$`cik`) == 0) || ((length(self$`cik`) != 0 && R6::is.R6(self$`cik`[[1]]))))) {
          FilingNoteFilingObject[['cik']] <- lapply(self$`cik`, function(x) x$toJSON())
        } else {
          FilingNoteFilingObject[['cik']] <- jsonlite::toJSON(self$`cik`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`report_type`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`report_type`) && ((length(self$`report_type`) == 0) || ((length(self$`report_type`) != 0 && R6::is.R6(self$`report_type`[[1]]))))) {
          FilingNoteFilingObject[['report_type']] <- lapply(self$`report_type`, function(x) x$toJSON())
        } else {
          FilingNoteFilingObject[['report_type']] <- jsonlite::toJSON(self$`report_type`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`period_end_date`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`period_end_date`) && ((length(self$`period_end_date`) == 0) || ((length(self$`period_end_date`) != 0 && R6::is.R6(self$`period_end_date`[[1]]))))) {
          FilingNoteFilingObject[['period_end_date']] <- lapply(self$`period_end_date`, function(x) x$toJSON())
        } else {
          FilingNoteFilingObject[['period_end_date']] <- jsonlite::toJSON(self$`period_end_date`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`filing_date`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`filing_date`) && ((length(self$`filing_date`) == 0) || ((length(self$`filing_date`) != 0 && R6::is.R6(self$`filing_date`[[1]]))))) {
          FilingNoteFilingObject[['filing_date']] <- lapply(self$`filing_date`, function(x) x$toJSON())
        } else {
          FilingNoteFilingObject[['filing_date']] <- jsonlite::toJSON(self$`filing_date`, auto_unbox = TRUE)
        }
      }

      FilingNoteFilingObject
    },
    fromJSON = function(FilingNoteFilingJson) {
      FilingNoteFilingObject <- jsonlite::fromJSON(FilingNoteFilingJson)
      if (!is.null(FilingNoteFilingObject$`cik`)) {
        self$`cik` <- FilingNoteFilingObject$`cik`
      }
      if (!is.null(FilingNoteFilingObject$`report_type`)) {
        self$`report_type` <- FilingNoteFilingObject$`report_type`
      }
      if (!is.null(FilingNoteFilingObject$`period_end_date`)) {
        self$`period_end_date` <- FilingNoteFilingObject$`period_end_date`
      }
      if (!is.null(FilingNoteFilingObject$`filing_date`)) {
        self$`filing_date` <- FilingNoteFilingObject$`filing_date`
      }
    },
    toJSONString = function() {
      jsonlite::toJSON(self$toJSON(), auto_unbox = TRUE, pretty = TRUE)
    },
    fromJSONString = function(FilingNoteFilingJson) {
      FilingNoteFilingObject <- jsonlite::fromJSON(FilingNoteFilingJson)
      self$`cik` <- FilingNoteFilingObject$`cik`
      self$`report_type` <- FilingNoteFilingObject$`report_type`
      DateObject <- Date$new()
      self$`period_end_date` <- DateObject$fromJSON(jsonlite::toJSON(FilingNoteFilingObject$period_end_date, auto_unbox = TRUE))
      DateObject <- Date$new()
      self$`filing_date` <- DateObject$fromJSON(jsonlite::toJSON(FilingNoteFilingObject$filing_date, auto_unbox = TRUE))
    }
  )
)
