# Intrinio API
#
# Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
#
# OpenAPI spec version: 2.9.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Filing8kItem Class
#'
#' @field code 
#' @field name 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Filing8kItem <- R6::R6Class(
  'Filing8kItem',
  public = list(
    `code` = NULL,
    `name` = NULL,
    initialize = function(`code`, `name`){
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      Filing8kItemObject <- list()
      if (!is.null(self$`code`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`code`) && ((length(self$`code`) == 0) || ((length(self$`code`) != 0 && R6::is.R6(self$`code`[[1]]))))) {
          Filing8kItemObject[['code']] <- lapply(self$`code`, function(x) x$toJSON())
        } else {
          Filing8kItemObject[['code']] <- jsonlite::toJSON(self$`code`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`name`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`name`) && ((length(self$`name`) == 0) || ((length(self$`name`) != 0 && R6::is.R6(self$`name`[[1]]))))) {
          Filing8kItemObject[['name']] <- lapply(self$`name`, function(x) x$toJSON())
        } else {
          Filing8kItemObject[['name']] <- jsonlite::toJSON(self$`name`, auto_unbox = TRUE)
        }
      }

      Filing8kItemObject
    },
    fromJSON = function(Filing8kItemJson) {
      Filing8kItemObject <- jsonlite::fromJSON(Filing8kItemJson)
      if (!is.null(Filing8kItemObject$`code`)) {
        self$`code` <- Filing8kItemObject$`code`
      }
      if (!is.null(Filing8kItemObject$`name`)) {
        self$`name` <- Filing8kItemObject$`name`
      }
    },
    toJSONString = function() {
      jsonlite::toJSON(self$toJSON(), auto_unbox = TRUE, pretty = TRUE)
    },
    fromJSONString = function(Filing8kItemJson) {
      Filing8kItemObject <- jsonlite::fromJSON(Filing8kItemJson)
      self$`code` <- Filing8kItemObject$`code`
      self$`name` <- Filing8kItemObject$`name`
    }
  )
)
