# Intrinio API
#
# Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.
#
# OpenAPI spec version: 2.9.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ForceIndexTechnicalValue Class
#'
#' @field date_time 
#' @field fi 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ForceIndexTechnicalValue <- R6::R6Class(
  'ForceIndexTechnicalValue',
  public = list(
    `date_time` = NULL,
    `fi` = NULL,
    initialize = function(`date_time`, `fi`){
      if (!missing(`date_time`)) {
        stopifnot(is.character(`date_time`), length(`date_time`) == 1)
        stopifnot(R6::is.R6(`date_time`))
        self$`date_time` <- `date_time`
      }
      if (!missing(`fi`)) {
        stopifnot(is.numeric(`fi`), length(`fi`) == 1)
        self$`fi` <- `fi`
      }
    },
    toJSON = function() {
      ForceIndexTechnicalValueObject <- list()
      if (!is.null(self$`date_time`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`date_time`) && ((length(self$`date_time`) == 0) || ((length(self$`date_time`) != 0 && R6::is.R6(self$`date_time`[[1]]))))) {
          ForceIndexTechnicalValueObject[['date_time']] <- lapply(self$`date_time`, function(x) x$toJSON())
        } else {
          ForceIndexTechnicalValueObject[['date_time']] <- jsonlite::toJSON(self$`date_time`, auto_unbox = TRUE)
        }
      }
      if (!is.null(self$`fi`)) {
        # If the object is an empty list or a list of R6 Objects
        if (is.list(self$`fi`) && ((length(self$`fi`) == 0) || ((length(self$`fi`) != 0 && R6::is.R6(self$`fi`[[1]]))))) {
          ForceIndexTechnicalValueObject[['fi']] <- lapply(self$`fi`, function(x) x$toJSON())
        } else {
          ForceIndexTechnicalValueObject[['fi']] <- jsonlite::toJSON(self$`fi`, auto_unbox = TRUE)
        }
      }

      ForceIndexTechnicalValueObject
    },
    fromJSON = function(ForceIndexTechnicalValueJson) {
      ForceIndexTechnicalValueObject <- jsonlite::fromJSON(ForceIndexTechnicalValueJson)
      if (!is.null(ForceIndexTechnicalValueObject$`date_time`)) {
        self$`date_time` <- ForceIndexTechnicalValueObject$`date_time`
      }
      if (!is.null(ForceIndexTechnicalValueObject$`fi`)) {
        self$`fi` <- ForceIndexTechnicalValueObject$`fi`
      }
    },
    toJSONString = function() {
      jsonlite::toJSON(self$toJSON(), auto_unbox = TRUE, pretty = TRUE)
    },
    fromJSONString = function(ForceIndexTechnicalValueJson) {
      ForceIndexTechnicalValueObject <- jsonlite::fromJSON(ForceIndexTechnicalValueJson)
      POSIXltObject <- POSIXlt$new()
      self$`date_time` <- POSIXltObject$fromJSON(jsonlite::toJSON(ForceIndexTechnicalValueObject$date_time, auto_unbox = TRUE))
      self$`fi` <- ForceIndexTechnicalValueObject$`fi`
    }
  )
)
